### ISSUE TITLE
我用之前的API KEY 出现未知错误

### ISSUE THREAD

**Issue by hellojazy** [iKaew/hass-lifesmart-addon#17]

**Comment by hellojazy** [comment]
不知道是api的问题还是什么。 API在之前skyzhishui的插件可以正常使用 。现在新申请的api还没审核过。请帮忙看看，谢谢

Unknown error occurred

此错误来自自定义集成。

日志: custom_components.lifesmart.config_flow
来源: custom_components/lifesmart/config_flow.py:101
集成: LifeSmart (文档, 问题)
首次发生: 21:56:55 (7 全部发生)
上次记录: 22:11:49

Input validation error


-----------------------------------

 File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lifesmart/config_flow.py", line 104, in async_step_user
    await self.async_set_unique_id(validated["unique_id"])
                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'validated' where it is not associated with a value

**Comment by hellojazy** [comment]
看APP 三方授权 是授权通过了。但是前台就报错Unknown error occurred

**Comment by iKaew** [comment]
Which version that you installed? The latest version of the add-on changes to use user id with password rather than user token.

**Comment by hellojazy** [comment]
The latest version,It's the user password,I found in the APP that the authorization is complete,But the front desk reports an error.。 I don't know if it has anything to do with the api key, but I used the key from 2 years ago

**Comment by iKaew** [comment]
Look like there is an error when migrate the configuration. Can you remove the device and add it back again ?

**Comment by iKaew** [comment]
Please re-add the hub

**Comment by iKaew** [comment]
Is it solved your issue ?
